# -*- coding: utf-8 -*-
"""1.Chroma_DB_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jc7SUGM67fwaBflknfBUVa8FFeZvlAtT
"""

print("OK!")

!pip -q install chromadb openai langchain tiktoken

!pip show chromadb

!wget -q https://www.dropbox.com/s/vs6ocyvpzzncvwh/new_articles.zip

!unzip -q new_articles.zip -d new_articles

"""## Setting up Environment"""

import os
from openai import OpenAI

# Set your API key. You should store this securely,
# for example, in Colab Secrets or a .env file.
# For this example, I'll put it directly here, but
# this is NOT recommended for production code.
os.environ['OPENAI_API_KEY'] = "FY28tH---key"

"""## Import some libraries"""

from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.document_loaders import DirectoryLoader
from langchain.document_loaders import TextLoader

pip install -U langchain-community

"""## Load data"""

loader = DirectoryLoader("/content/new_articles/", glob = "./*.txt", loader_cls= TextLoader)

document = loader.load()

document

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 1000, chunk_overlap = 200)
text = text_splitter.split_documents(document)

text

len(text)

text[1]

text[2]

"""## Creating DB"""

from langchain import embeddings
persist_directory = 'db'

embedding = OpenAIEmbeddings()

vectordb = Chroma.from_documents(documents=text,
                                 embedding=embedding,
                                 persist_directory=persist_directory)

# persiste the db to disk
vectordb.persist()
vectordb = None

# Now we can load the persisted database from disk, and use it as normal.
vectordb = Chroma(persist_directory=persist_directory,
                  embedding_function=embedding)

"""## Make a retriever"""

retriever = vectordb.as_retriever()

docs = retriever.get_relevant_documents("How much money did Microsoft raise?")

len(docs)

docs

retriever = vectordb.as_retriever(search_kwargs={"k": 2})

retriever.search_type

retriever.search_kwargs

"""## Make a chain"""

from langchain.chains import RetrievalQA

llm=OpenAI()

llm

# create the chain to answer questions
qa_chain = RetrievalQA.from_chain_type(llm=OpenAI(),
                                  chain_type="stuff",
                                  retriever=retriever,
                                  return_source_documents=True)

## Cite sources
def process_llm_response(llm_response):
    print(llm_response['result'])
    print('\n\nSources:')
    for source in llm_response["source_documents"]:
        print(source.metadata['source'])

# full example
query = "How much money did Microsoft raise?"
llm_response = qa_chain(query)
process_llm_response(llm_response)

# break it down
query = "What is the news about Pando?"
llm_response = qa_chain(query)
process_llm_response(llm_response)

"""## Deleteing the DB

"""

!zip -r db.zip ./db

# To cleanup, you can delete the collection
vectordb.delete_collection()
vectordb.persist()

# delete the directory
!rm -rf db/

"""## Starting again loading the db"""

!unzip db.zip

