# -*- coding: utf-8 -*-
"""EYday1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLuSUQqXWU55wCEw77MRueCiSahaSDas
"""

!pip install -q langchain langchain-openai openai

import os
from getpass import getpass

# Secure API key input
os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API Key: ")

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.3   # Lower = more deterministic (better for DE)
)

print("LLM is ready ✅")

import pandas as pd

df = pd.read_csv("dirty_transaction_data.csv")
df.head()

!pip install ydata-profiling
from ydata_profiling import ProfileReport

profile = ProfileReport(df, explorative=True)
profile.to_file("report.html")

summary = df.describe().to_string()

prompt = f"""
Analyze this dataset summary and explain:
- Key columns
- Data quality issues
- Potential anomalies

{summary}
"""
response = llm.invoke(prompt)
print(response.content)

summary = df.describe().to_string()

prompt = f"""
You are a data engineer analyzing a dataset.

Identify:
- Key columns
- Data quality issues
- Missing values
- Anomalies

Dataset Summary:
{summary}
"""

print(ask_llm(prompt))

def ask_llm(prompt):
    try:
        response = llm.invoke(prompt)
        return response.content
    except Exception as e:
        return f"ERROR: {str(e)}"

schema_info = df.dtypes.to_string()

prompt = f"""
Create a data dictionary.

For each column:
- Business meaning
- Better column name
- Category

Schema:
{schema_info}
"""

print(ask_llm(prompt))

sql_query = """
SELECT customer_id, SUM(amount) AS total_revenue
FROM sales
GROUP BY customer_id
"""

prompt = f"""
Generate Source-to-Target Mapping:

Include:
- Source fields
- Transformation logic
- Target fields

SQL:
{sql_query}
"""

print(ask_llm(prompt))